- import_tasks: preflight.yml

- import_tasks: install.yml
  become: yes

- import_tasks: configure.yml
  become: yes

- name: Ensure Node Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
