---

- block:
  - name: Get latest release
    uri:
      url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
      method: GET
      return_content: true
      status_code: 200
      body_format: json
      user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
      password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
    register: _latest_release
    until: _latest_release.status == 200
    retries: 5

  - name: "Set node_exporter version to {{ _latest_release.json.tag_name[1:] }}"
    set_fact:
      node_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
    when:
      - node_exporter_version == "latest"
      - node_exporter_binary_local_dir | length == 0
    delegate_to: localhost
    run_once: true
  - block:
    - name: Get checksum list from github
      set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/prometheus/node_exporter/releases/download/v' + node_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
        run_once: true

    - name: "Get checksum for {{ go_arch }} architecture"
      set_fact:
        node_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - "('linux-' + go_arch + '.tar.gz') in item"
    delegate_to: localhost
    when: node_exporter_binary_local_dir | length == 0
