- name: install dependencies
  block:
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: true
    - name: install software-properties-common
      apt:
        name: software-properties-common
    - name: install wget
      apt:
        name: wget
    - name: install grafana repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    - name: add grafana repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: true

- name: install grafana
  apt:
    name: grafana

- name: enable grafana service
  systemd:
    name: grafana-server
    enable: true
    state: started

  



