- name: create users, groups and directories
  become: true
  become_user: root
  block:
    - name: create prometheus group
      group:
        name: prometheus
        system: true
        state: present

    - name: create prometheus user
      user:
        name: prometheus
        groups: prometheus
        shell: /sbin/nologin
        system: true

    - name: create prometheus directory
      block:
        - name: /var/lib/prometheus 
          file:
            path: /var/lib/prometheus
            state: directory
            mode: '0755'
        - name: /var/lib/prometheus/rules 
          file:
            path: /var/lib/prometheus/rules
            state: directory
            mode: '0755'
        - name: /var/lib/prometheus/rules.d
          file:
            path: /var/lib/prometheus/rules.d
            state: directory
            mode: '0755'
        - name: /var/lib/prometheus/files_sd 
          file:
            path: /var/lib/prometheus/files_sd
            state: directory
            mode: '0755'

- name: install prometheus
  become: true
  become_user: root
  block:
    - name: update apt cache
      apt:
        update_cache: yes
    - name: install wget
      apt:
        name: wget
        state: present
    - name: install curl 
      apt:
        name: curl
        state: present
    - name: install vim
      apt:
        name: vim
        state: present
    - name: create install directory
      file:
        path: /tmp/prometheus
        state: directory
        mode: '0755'
    - name: install lastest prometheus
      block:
        - name: download latest
          comand: curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 | wget -qi -
          chdir: /tmp/prometheus/

        - name: untar tarfile
          unarchive:
            src: /temp/prometheus/prometheus*.tar.gz
            dest: /temp/prometheus/

        - name: copy prometheus to bin
          copy:
            remote_src: true
            src: /temp/prometheus/prometheus
            dest: /usr/local/bin/prometheus

        - name: move promtool to bin
          copy:
            remote_src: true
            src: /temp/prometheus/promtool
            dest: /usr/local/bin/promtool


        - name: copy consoles to etc
          copy:
            remote_src: true
            src: /temp/prometheus/consoles
            dest: /etc/prometheus/consoles

        - name: move console_library to etc
          copy:
            remote_src: true
            src: /temp/prometheus/console_libraries
            dest: /etc/prometheus/console_libraries

    - name: configure prometheus
      block:
        - name: change ownership of /var/lip/prometheus
          file:
            state: directory 
            path: /var/lib/prometheus
            owner: prometheus
            group: prometheus

        - name: copy prometheus.yml config
          copy: 
            src: files/prometheus.yml
            dest: /etc/prometheus/prometheus.yml
            mode: '775'
            owner: prometheus

        - name: copy prometheus.service
          copy:
            src: files/prometheus.service
            dest: /etc/systemd/system/prometheus.service

        - name: enable and start prometheus service 
          systemd:
            name: prometheus
            daemon_reload: true
            enabled: true
            state: started

